=== adriianluna/LLMM/tema5/PracticaValidacionesXML2/ejercicio4.3/doctype.dtd
<!ELEMENT restaurante (menu,recetas,clientes)>

<!-- Menu-->
<!ELEMENT menu (plato+)>
<!ELEMENT plato (nombrePlato, categoria,lista_ingredientes,precio)>
<!ELEMENT nombrePlato (#PCDATA)>

<!ELEMENT categoria (#PCDATA)>
<!ATTLIST categoria tipo CDATA #REQUIRED>

<!ELEMENT lista_ingredientes (ingredientes+)>
<!ELEMENT ingredientes (#PCDATA)>

<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio moneda (USD|EUR) #REQUIRED>


<!ELEMENT recetas (receta+)>

<!ELEMENT receta (nombre,lista_ingredientesR,preparacion)>
<!ATTLIST receta tipoComersales (adulto|niÃ±o) #REQUIRED>

<!ELEMENT lista_ingredientesR (ingrediente)>
<!ELEMENT ingrediente (#PCDATA)>
<!ATTLIST ingrediente cantidad CDATA #REQUIRED>
<!ATTLIST ingrediente nombreIngrediente CDATA #REQUIRED>

<!ELEMENT preparacion (pasos+)>
<!ELEMENT pasos (#PCDATA)>

<!ELEMENT clientes (cliente+)>
<!ELEMENT cliente (nombre,telefono,email,pedidos)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT pedidos (pedido+)>
<!ELEMENT pedido (#PCDATA)>
<!ATTLIST pedido fecha CDATA #REQUIRED>
<!ATTLIST pedido patosPedidos CDATA #REQUIRED>

=== adriianluna/LLMM/tema5/PracticaValidacionesXML2/ejercicio4.3/restaurante.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE restaurante SYSTEM "doctype.dtd">

<restaurante>
    <menu>
            <plato>
               <nombrePlato></nombrePlato>
                <categoria tipo="postre"></categoria>
                <lista_ingredientes>
                    <ingredientes></ingredientes>
                </lista_ingredientes>
                <precio moneda="USD"></precio>


            </plato>
            <plato>
               <nombrePlato></nombrePlato>
                <categoria tipo="postre"></categoria>
                <lista_ingredientes>
                    <ingredientes ></ingredientes>
                </lista_ingredientes>
                <precio moneda="USD"></precio>


            </plato>   
    
    </menu>
    <recetas>
        <receta tipoComersales ="adulto">
            <nombre></nombre>
            
            <lista_ingredientesR>
                <ingrediente nombreIngrediente="" cantidad="200"></ingrediente>


            </lista_ingredientesR>
            <preparacion>
                <pasos></pasos>
            </preparacion>


        </receta>
    
    
    
    
    </recetas>
    <clientes>
        <cliente>
            <nombre></nombre>
            <telefono></telefono>
            <email></email>
            <pedidos>
                <pedido fecha="" patosPedidos=""></pedido>
        
            </pedidos>

        </cliente>
    
    </clientes>



</restaurante>
