=== adriianluna/LLMM/tema5/PracticaValidacionesXML2/Pruebas/prueba3/doctype.dtd
<!ELEMENT eventos (evento+)>

<!ELEMENT evento (presencial)>

<!-- <!ELEMENT presencial ((direccion|sala) | (plataforma|enlace))>-->
<!ELEMENT presencial ((direccion,sala+) | (plataforma,enlace))>

<!ELEMENT direccion (#PCDATA)>
<!ELEMENT sala (#PCDATA)>
<!ELEMENT plataforma (#PCDATA)>
<!ELEMENT enlace (#PCDATA)>

=== adriianluna/LLMM/tema5/PracticaValidacionesXML2/Pruebas/prueba3/respuestas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eventos SYSTEM "doctype.dtd">
<eventos>
    <evento>
        <presencial>
            <direccion>Calle Falsa 123</direccion>
            <sala>Auditorio 2</sala>
          <sala>Auditorio 2</sala>
        </presencial>
    </evento>

    <evento>
        <presencial>
            <plataforma>Zoom</plataforma>
            <enlace>https://zoom.us/j/123456789</enlace>
        </presencial>
    </evento>
</eventos>
