=== adriianluna/LLMM/tema5/PracticaValidacionesXML2/Pruebas/prueba2/doctype.dtd
<!ELEMENT biblioteca (libro+)>

<!ELEMENT libro (titulo,autor,extra)>

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT extra (premio?,comentario?,reseña?)>


<!ELEMENT premio (#PCDATA)>
<!ELEMENT comentario (#PCDATA)>
<!ELEMENT reseña (#PCDATA)>

=== adriianluna/LLMM/tema5/PracticaValidacionesXML2/Pruebas/prueba2/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "doctype.dtd">
<biblioteca>
    <libro>
        <titulo>1984</titulo>
        <autor>George Orwell</autor>
        <extra>
            <premio>Año 1950</premio>
        </extra>
    </libro>
    <libro>
        <titulo>El Principito</titulo>
        <autor>Antoine de Saint-Exupéry</autor>
        <extra>
            <comentario>Lectura recomendada para todas las edades.</comentario>
            <reseña>Poesía en forma de cuento.</reseña>
        </extra>
    </libro>
</biblioteca>
