=== adriianluna/LLMM/tema5/PracticaValidacionesXML/ejercicio4.2/doctype.dtd
<!ELEMENT restaurante (menu, recetas,clientes)>

<!-- menu-->
<!ELEMENT menu (plato+)>
<!ELEMENT plato (nombre,categoria,lista_ingredientes, precio)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT categoria (#PCDATA)>
<!ELEMENT lista_ingredientes (#PCDATA)>
<!ELEMENT precio (#PCDATA)>

<!-- Atributo precio-->
<!ATTLIST precio moneda (USD|EUR|GBP) #REQUIRED>

<!-- Recetas-->
<!ELEMENT recetas (receta)>
<!ELEMENT receta (nombre2,comersales,lista_ingredientes,pasos,ingredientes)>
<!ELEMENT nombre2 (#PCDATA)>
<!ELEMENT comersales (#PCDATA)>
<!ATTLIST comersales tipo ID #REQUIRED>

<!ELEMENT pasos (paso)>
<!ELEMENT paso (#PCDATA)>


<!ELEMENT ingredientes (nombre3)>
<!ELEMENT nombre3 (#PCDATA)>

<!-- atributo-->
<!ATTLIST nombre3 cantidad CDATA #REQUIRED>


<!ELEMENT clientes (cliente)>
<!ELEMENT cliente (nombre4,telefono,email,pedidos)>

<!ELEMENT nombre4 (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT pedidos (fecha,platos_pedidos)>

<!ELEMENT fecha (#PCDATA)>
<!ELEMENT platos_pedidos (#PCDATA)>

=== adriianluna/LLMM/tema5/PracticaValidacionesXML/ejercicio4.3/restaurante.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE restaurante SYSTEM "doctype.dtd">
<restaurante>
    <menu>
        <plato>
            <nombre></nombre>
            <categoria></categoria>
            <lista_ingredientes></lista_ingredientes>
            <precio moneda="USD"></precio>
        </plato>
        <plato>
            <nombre></nombre>
            <categoria></categoria>
            <lista_ingredientes></lista_ingredientes>
            <precio moneda="USD"></precio>
        </plato>

    </menu>
    <recetas>
        <receta>
            <nombre2></nombre2>
            <comersales tipo="adultos"></comersales>
            <lista_ingredientes></lista_ingredientes>
            <pasos>
                <paso> </paso>

            </pasos>
            <ingredientes>
                <nombre3 cantidad="200"> </nombre3>

            </ingredientes>

        </receta>


    </recetas>

    <clientes>
        <cliente>
            <nombre4></nombre4>
            <telefono></telefono>
            <email></email>
            <pedidos>
                <fecha></fecha>
                <platos_pedidos></platos_pedidos>
            </pedidos>

        </cliente>


    </clientes>


</restaurante>
