=== adriianluna/LLMM/tema5/ValidacionesXML/ejercicio4.3/doctype.dtd
<!ELEMENT restaurante (menu,recetas,clientes)>
 
 <!-- Platos-->
 <!ELEMENT menu (platos+)>
 <!ELEMENT platos (plato*)>
 <!ELEMENT plato (nombrePlato,categoria,ingredientes,precio)>
 <!ELEMENT nombrePlato (#PCDATA)>
 <!ELEMENT categoria (#PCDATA)>
 <!ELEMENT ingredientes (ingrediente+)>
 <!ELEMENT ingrediente (#PCDATA)>
 <!ELEMENT precio (#PCDATA)>

 <!-- Para precio-->
<!ATTLIST precio moneda (USD|EUR|GBP) #REQUIRED>

<!-- Recetas-->
 <!ELEMENT recetas (receta+)>
 <!ELEMENT receta (nombreReceta,ingredientesReceta,preparacion)>
 <!ELEMENT nombreReceta (#PCDATA)>
<!ELEMENT ingredientesReceta (ingrediente2+)>
 <!ELEMENT ingrediente2 (#PCDATA)>
 <!ELEMENT preparacion (pasos+)>
 <!ELEMENT pasos (#PCDATA)> 

  <!-- Para receta-->
  <!ATTLIST nombreReceta comersal (niÃ±os|adultos) #REQUIRED>
    <!-- Para receta ingrediente-->
    <!-- Lo que sea sin ser obligatorio-->
 <!ATTLIST ingrediente2 nombre CDATA #IMPLIED>

  <!-- Para receta ingrediente-->
 <!ATTLIST ingrediente2 cantidad CDATA #REQUIRED> 

<!-- Clientes-->
 <!ELEMENT clientes (cliente+)>
 <!ELEMENT cliente (nombreCliente,telefono,email, pedidos)>
 <!ELEMENT nombreCliente (#PCDATA)>
 <!ELEMENT telefono (#PCDATA)>
 <!ELEMENT email (#PCDATA)>
 <!ELEMENT pedidos (pedido*)>
 <!ELEMENT pedido (#PCDATA)>
  
  <!-- Para pedido-->
  <!ATTLIST pedido fecha CDATA #IMPLIED>
   <!-- Para precio-->
  <!ATTLIST pedido patosPedidos CDATA #IMPLIED>

=== adriianluna/LLMM/tema5/ValidacionesXML/ejercicio4.3/fichero.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE restaurante SYSTEM "doctype.dtd">
<restaurante>
    <menu>
        <platos>
            <plato>
                <nombre></nombre>
                <categoria></categoria>
                <ingredientes>
                    <ingrediente></ingrediente>

                </ingredientes>
                <precio moneda="USD"></precio>
            </plato>
            

        </platos>
    </menu>
    <recetas>
        <receta>
            <nombre comersal="niÃ±os"></nombre>
            <ingredientes>
                <ingrediente nombre = "" cantidad="200"></ingrediente>

            </ingredientes>
            <preparacion>
                <pasos></pasos>
                <pasos></pasos>
                <pasos></pasos>
        </preparacion>
        </receta>
        
    
    
    </recetas>
    <clientes>
        <cliente>
            <nomrbe></nomrbe>
            <telefono></telefono>
            <email></email>
            <pedidos>
                <pedido fecha="" pedidos=""></pedido>
        
            </pedidos>
        </cliente>
       


    </clientes>
</restaurante>
